# 

services:
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: example
            POSTGRES_DB: cv_db
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./initdb:/docker-entrypoint-initdb.d
    
    qdrant:
        image: qdrant/qdrant:latest
        container_name: qdrant
        ports:
            - "6333:6333"
            - "6334:6334"
        volumes:
            - qdrant_data:/qdrant/storage
        environment:
            QDRANT__SERVICE__GRPC_PORT: 6334
            QDRANT__SERVICE__HTTP_PORT: 6333

volumes:
    db_data:
        driver: local
    qdrant_data:
        driver: local
